#!/usr/bin/env python3
"""Render the landing page from site/src/ templates and site/brand.json.

The product name lives only in brand.json. Templates use {{placeholders}}; this
script fills them and writes site/<template>.html (index.html, welcome.html). It refuses to build if the name
has leaked into a template, stylesheet or script, so a rename stays one line.

    python3 site/build.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

SITE = Path(__file__).resolve().parent
SRC = SITE / "src"
GUARDED = [*SRC.glob("*.html"), *(SITE / "assets").glob("*.css"), *(SITE / "assets").glob("*.js")]
PLACEHOLDER = re.compile(r"\{\{\s*([a-z_]+)\s*\}\}")
INSTALLER = SITE.parent / "scripts" / "install.sh"
DEFAULT_VERSION = re.compile(r'^DEFAULT_VERSION="(v[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?)"$', re.MULTILINE)


def installer_version() -> str:
    """The release the site's installer installs by default (one line in scripts/install.sh), without the "v"."""
    found = DEFAULT_VERSION.findall(INSTALLER.read_text(encoding="utf-8"))
    if len(found) != 1:
        sys.exit(f"scripts/install.sh: expected exactly one DEFAULT_VERSION=\"vX.Y.Z\" line, found {len(found)}")
    return found[0][1:]


def load_brand() -> dict[str, str]:
    raw = json.loads((SITE / "brand.json").read_text(encoding="utf-8"))
    name = str(raw.get("name", "")).strip()
    if not name:
        sys.exit("brand.json: 'name' is required")
    cli = str(raw.get("cli") or name.lower()).strip()
    if not re.fullmatch(r"[a-z][a-z0-9-]*", cli):
        sys.exit(f"brand.json: CLI command {cli!r} must be lowercase letters, digits or dashes (set 'cli' explicitly)")
    owner = str(raw.get("github_owner", "")).strip()
    repo = str(raw.get("repo") or f"{owner}/{cli}")
    site_url = str(raw.get("site_url", "")).rstrip("/")
    tagline = str(raw.get("tagline", "")).strip()
    # A HEAD response only proves bytes exist. WALK-50 must supply a verified signing and
    # notarization receipt before this action can be enabled in a generated production page.
    package_available = False
    return {
        "name": name,
        "cli": cli,
        "tagline": tagline,
        "version": installer_version(),
        "release_version": "v" + installer_version(),
        "package_available": "true" if package_available else "false",
        "package_hidden": "" if package_available else "hidden",
        "fallback_open": "" if package_available else "open",
        # "0.2.0-pre.3 (pre-release)" for a semver prerelease, else the bare version: footer and install note.
        "release": installer_version() + (" (pre-release)" if "-" in installer_version() else ""),
        "repo": repo,
        "github_owner": owner,
        # The public source repository (FSL-1.1-ALv2): nav and footer links.
        "source_url": f"https://github.com/{repo}",
        "install": f"curl -fsSL {site_url}/install.sh | sh" if site_url else "curl -fsSL /install.sh | sh",
        "install_url": f"{site_url}/install.sh" if site_url else "/install.sh",
        "og_image": f"{site_url}/assets/img/og.jpg" if site_url else "assets/img/og.jpg",
        "canonical": f'<link rel="canonical" href="{site_url}/">' if site_url else "",
        "og_url": f'<meta property="og:url" content="{site_url}/">' if site_url else "",
    }


def guard(name: str, cli: str) -> None:
    needles = {name.lower(), cli.lower()}
    leaks = []
    for path in GUARDED:
        text = path.read_text(encoding="utf-8").lower()
        for needle in needles:
            if re.search(rf"\b{re.escape(needle)}\b", text):
                leaks.append(f"{path.relative_to(SITE)} contains {needle!r}")
    if leaks:
        sys.exit("The product name must only live in brand.json. Use {{name}} / {{cli}} instead:\n  " + "\n  ".join(leaks))


def render(template: str, values: dict[str, str]) -> str:
    def sub(match: re.Match[str]) -> str:
        key = match.group(1)
        if key not in values:
            sys.exit(f"unknown placeholder {{{{{key}}}}}")
        return values[key]

    return PLACEHOLDER.sub(sub, template)


def main() -> None:
    values = load_brand()
    guard(values["name"], values["cli"])
    for template in sorted(SRC.glob("*.html")):
        out = SITE / template.name
        html = render(template.read_text(encoding="utf-8"), values)
        banner = f"<!-- Generated by site/build.py from site/src/{template.name}. Edit the source, not this file. -->\n"
        out.write_text(banner + html, encoding="utf-8")
        print(f"wrote {out.relative_to(SITE.parent)} ({len(html.encode()):,} bytes) as {values['name']!r} / {values['cli']!r}")
    # The installer is served from the site (https://<site>/install.sh); scripts/install.sh is the source.
    (SITE / "install.sh").write_bytes(INSTALLER.read_bytes())
    print("copied scripts/install.sh -> site/install.sh")


if __name__ == "__main__":
    main()
