import { leaseUnits, METADATA_SCRIPT } from './guest-safety.js';
// The user-data a rented machine boots with (docs/plans/RENT-1.md §6.1, §6.3). Provider-neutral bash for a stock
// Ubuntu LTS image. It:
//   1. keeps the per-rental heartbeat token in a root-only file,
//   2. blocks the instance metadata endpoint (where this user-data can be re-read) for every user but root,
//   3. shapes egress to the public fair-use rate (tc tbf) — the hard monthly cap is enforced by the control plane from
//      the heartbeat's byte count, and any provider firewall is the driver's job,
//   4. installs the PINNED, SIGNED Walkie release with the official installer (it verifies the ECDSA signature and
//      the checksum before anything runs) as an unprivileged `walkie` user, joining the team with the one-time,
//      1-hour add-machine code, with team agents allowed (seat users; never same-user) — the renting owner consented,
//   0. installs git, a build toolchain and the Claude Code / Codex CLIs that seats run (no logins),
//   5. deletes its own copy of the user-data, drops the bootstrap sudo rule, and starts a once-a-minute heartbeat.
// It carries no logins: seats lease the team's own accounts from the company pool when the team turns the pool on.
// Every interpolated value is validated against a strict pattern first, so none can break out of its quotes.
import { JOIN_CODE, RELEASE_TAG, RENTAL_ID, TOKEN } from "./types.js";

export interface BootParams {
  readonly leaseUntil?: number;
  readonly rentalId: string;
  readonly joinCode: string;
  readonly heartbeatToken: string;
  readonly walkieVersion: string;
  readonly siteOrigin: string;
  readonly hostname: string;
  readonly egressRateMbit: number;
}

const HOSTNAME = /^rent-[a-z0-9-]{1,40}$/;
const ORIGIN = /^https:\/\/[a-z0-9.-]{1,253}(?::\d{1,5})?$/;

export function checkBootParams(p: BootParams): void {
  if (p.leaseUntil !== undefined && (!Number.isSafeInteger(p.leaseUntil) || p.leaseUntil <= 0)) throw new Error('bad lease');
  if (!RENTAL_ID.test(p.rentalId)) throw new Error("bad rental id");
  if (!JOIN_CODE.test(p.joinCode)) throw new Error("bad join code");
  if (!TOKEN.test(p.heartbeatToken)) throw new Error("bad heartbeat token");
  if (!RELEASE_TAG.test(p.walkieVersion)) throw new Error("bad walkie version");
  if (!ORIGIN.test(p.siteOrigin)) throw new Error("bad site origin");
  if (!HOSTNAME.test(p.hostname)) throw new Error("bad hostname");
  if (!Number.isInteger(p.egressRateMbit) || p.egressRateMbit < 1 || p.egressRateMbit > 100_000) throw new Error("bad egress rate");
}

const HEARTBEAT = `#!/bin/bash
# Walkie rental heartbeat: liveness and load, once a minute, as root.
set -u
. /etc/walkie-rental/env
busy=$(ps -eo user= | grep -E '^walkie-s[0-9]+$' | sort -u | wc -l | tr -d ' ')
pool=$(pgrep -c -f 'rpc-server|llama-server' || true)
read -r _ u n s i w q sq st _ < /proc/stat; t1=$((u+n+s+i+w+q+sq+st)); i1=$((i+w)); sleep 1
read -r _ u n s i w q sq st _ < /proc/stat; t2=$((u+n+s+i+w+q+sq+st)); i2=$((i+w))
cpu=0; [ $((t2-t1)) -gt 0 ] && cpu=$(( (100*((t2-t1)-(i2-i1))) / (t2-t1) ))
gpu=""
if command -v nvidia-smi >/dev/null 2>&1; then gpu=$(nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits | sort -nr | head -1 | tr -d ' '); fi
tx=0
for f in /sys/class/net/*/statistics/tx_bytes; do case "$f" in */lo/*) ;; *) tx=$((tx + $(cat "$f")));; esac; done
# Persist a cumulative counter across guest reboots; a systemd oneshot serializes writes.
boot=$(cat /proc/sys/kernel/random/boot_id)
prev_boot=""; prev_tx=0; total=0
[ ! -f /etc/walkie-rental/egress-total ] || read -r prev_boot prev_tx total < /etc/walkie-rental/egress-total
if [ "$boot" = "$prev_boot" ] && [ "$tx" -ge "$prev_tx" ]; then delta=$((tx-prev_tx)); else delta=$tx; fi
total=$((total+delta))
printf '%s %s %s\\n' "$boot" "$tx" "$total" > /etc/walkie-rental/egress-total.tmp
mv /etc/walkie-rental/egress-total.tmp /etc/walkie-rental/egress-total
tx=$total
gpu_json=""; [ -n "$gpu" ] && gpu_json=",\\"gpu_pct\\":$gpu"
body="{\\"rental_id\\":\\"$RENTAL_ID\\",\\"busy_seats\\":\${busy:-0},\\"pool_jobs\\":\${pool:-0},\\"cpu_pct\\":\${cpu:-0}$gpu_json,\\"egress_bytes\\":$tx}"
printf '%s' "$body" | curl -fsS --max-time 20 --header @/etc/walkie-rental/heartbeat-header -H 'content-type: application/json' --data-binary @- "$SITE/api/compute/heartbeat" >/dev/null || true
`;

export function userData(p: BootParams): string {
  checkBootParams(p);
  return `#!/bin/bash
# Walkie rented machine ${p.hostname} (${p.rentalId}). Generated by the Walkie control plane.
set -euo pipefail
umask 077
hostnamectl set-hostname '${p.hostname}' || true

install -d -m 0700 /etc/walkie-rental
printf '%s' '${p.heartbeatToken}' > /etc/walkie-rental/heartbeat-token
printf 'RENTAL_ID=%s\\nSITE=%s\\n' '${p.rentalId}' '${p.siteOrigin}' > /etc/walkie-rental/env

printf 'Authorization: Bearer %s\\n' "$(cat /etc/walkie-rental/heartbeat-token)" > /etc/walkie-rental/heartbeat-header
chmod 0600 /etc/walkie-rental/heartbeat-header /etc/walkie-rental/heartbeat-token
${leaseUnits(p.leaseUntil ?? Date.now() + 900_000)}
# Prerequisites and firewall are mandatory. Any failure exits before admitting work.
export DEBIAN_FRONTEND=noninteractive
bootstrap_failed() {
  printf 'Walkie bootstrap failed; work admission disabled\\n' >&2
  curl -fsS --max-time 20 --header @/etc/walkie-rental/heartbeat-header -H 'content-type: application/json' --data-binary '{"rental_id":"${p.rentalId}","bootstrap_failed":true,"busy_seats":0,"pool_jobs":0,"cpu_pct":0,"egress_bytes":0}' '${p.siteOrigin}/api/compute/heartbeat' >/dev/null 2>&1 || true
  exit 1
}
trap bootstrap_failed ERR
if [ -f /etc/apt/sources.list ]; then sed -i 's@mirrors.digitalocean.com@archive.ubuntu.com@g' /etc/apt/sources.list; fi
if [ -d /etc/apt/sources.list.d ]; then find /etc/apt/sources.list.d -type f -exec sed -i 's@mirrors.digitalocean.com@archive.ubuntu.com@g' {} +; fi
apt-get update -y
apt-get install -y git curl ca-certificates build-essential nodejs npm iptables iproute2 sudo
# Block link-local metadata for all non-root guest processes, including forwarded/container traffic.
iptables -I OUTPUT -d 169.254.0.0/16 -m owner ! --uid-owner 0 -j REJECT
iptables -I FORWARD -d 169.254.0.0/16 -j REJECT
ip6tables -I OUTPUT -d fe80::/10 -m owner ! --uid-owner 0 -j REJECT
ip6tables -I FORWARD -d fe80::/10 -j REJECT
iptables -C OUTPUT -d 169.254.0.0/16 -m owner ! --uid-owner 0 -j REJECT
iptables -C FORWARD -d 169.254.0.0/16 -j REJECT
ip6tables -C OUTPUT -d fe80::/10 -m owner ! --uid-owner 0 -j REJECT
ip6tables -C FORWARD -d fe80::/10 -j REJECT
# Public fair-use bandwidth, independent of private provider limits.
IF=$(ip route show default | awk '{print $5; exit}')
[ -n "$IF" ]
tc qdisc replace dev "$IF" root tbf rate 1000mbit burst 256kbit latency 400ms
npm install -g @anthropic-ai/claude-code @openai/codex || true

# The unprivileged user that runs the Walkie daemon. Seat setup needs sudo once; the rule is removed after.
id walkie >/dev/null 2>&1 || useradd -m -s /bin/bash walkie
printf 'walkie ALL=(ALL) NOPASSWD:ALL\\n' > /etc/sudoers.d/90-walkie-bootstrap
chmod 0440 /etc/sudoers.d/90-walkie-bootstrap
# Restore and verify isolation before the user's service manager can admit work after reboot.
iptables-save > /etc/walkie-rental/firewall-v4
ip6tables-save > /etc/walkie-rental/firewall-v6
cat > /usr/local/lib/walkie-rental/metadata.sh <<'METADATA'
${METADATA_SCRIPT}METADATA
chmod 0700 /usr/local/lib/walkie-rental/metadata.sh
cat > /etc/systemd/system/walkie-metadata.service <<'UNIT'
[Unit]
Description=Walkie mandatory metadata isolation
Before=systemd-user-sessions.service
After=cloud-init-local.service cloud-init.service cloud-config.service
[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/lib/walkie-rental/metadata.sh
[Install]
WantedBy=multi-user.target
UNIT
install -d -m 0755 /etc/systemd/system/user@.service.d
cat > /etc/systemd/system/user@.service.d/walkie-metadata.conf <<'UNIT'
[Unit]
Requires=walkie-metadata.service
After=walkie-metadata.service
UNIT
systemctl daemon-reload
systemctl enable --now walkie-metadata.service
loginctl enable-linger walkie

sudo -u walkie -H bash -c 'curl -fsSL ${p.siteOrigin}/install.sh | WALKIE_VERSION=${p.walkieVersion} sh -s -- --invite ${p.joinCode} --allow-team-agents --seat-users'

rm -f /etc/sudoers.d/90-walkie-bootstrap
# The join code is spent; drop cloud-init's copies of this script.
rm -f /var/lib/cloud/instance/user-data.txt /var/lib/cloud/instance/user-data.txt.i /var/lib/cloud/instance/scripts/part-* || true

install -d -m 0700 /usr/local/lib/walkie-rental
cat > /usr/local/lib/walkie-rental/heartbeat.sh <<'HB'
${HEARTBEAT}HB
chmod 0700 /usr/local/lib/walkie-rental/heartbeat.sh
cat > /etc/systemd/system/walkie-rental-heartbeat.service <<'UNIT'
[Unit]
Description=Walkie rental heartbeat
[Service]
Type=oneshot
ExecStart=/usr/local/lib/walkie-rental/heartbeat.sh
UNIT
cat > /etc/systemd/system/walkie-rental-heartbeat.timer <<'UNIT'
[Unit]
Description=Walkie rental heartbeat every minute
[Timer]
OnBootSec=30
OnUnitActiveSec=60
AccuracySec=5
[Install]
WantedBy=timers.target
UNIT
systemctl daemon-reload
systemctl enable --now walkie-rental-heartbeat.timer
`;
}
