// The iroh 1.x binding: n0's official Node-API SDK (@number0/iroh), loaded lazily so a Tailscale-only daemon
// never loads the native module. Release binaries embed the target's `.node` file (scripts/build.ts writes
// iroh-native.gen.ts with a static require of it, which `bun build --compile` embeds and extracts at run time).
import { createRequire } from "node:module";
import type * as Iroh from "@number0/iroh";

export type IrohModule = typeof Iroh;

// @ts-ignore -- generated by scripts/build.ts for release binaries; missing in source runs (the catch).
const embedded: (() => IrohModule) | null = await import("./iroh-native.gen.ts")
  .then((m: { default: () => IrohModule }) => m.default)
  .catch(() => null);

let loaded: IrohModule | null = null;

export function iroh(): IrohModule {
  if (loaded) return loaded;
  if (embedded) {
    loaded = embedded();
  } else {
    // A variable name keeps the bundler from following the SDK's per-platform optional requires.
    const pkg = "@number0/iroh";
    loaded = createRequire(import.meta.url)(pkg) as IrohModule;
  }
  return loaded;
}
