#!/usr/bin/env python3
# Regenerates src/switch/codex-cli-table.ts from `codex <path> --help` (ACCOUNTS-2 round 8).
# Usage: scripts/gen-codex-cli-table.py /path/to/codex > /dev/null  (writes the TS file; prints a summary)
import subprocess, re, json, sys, tempfile, os
B=sys.argv[1]  # the native codex binary to read
def help_of(path):
    r=subprocess.run([B,*path,"--help"],capture_output=True,text=True,timeout=20,env={"PATH":"/usr/bin:/bin","HOME":HOME,"CODEX_HOME":os.path.join(HOME,".codex"),"TERM":"dumb"})
    return r.stdout+r.stderr
def parse(txt):
    cmds=[]; opts={}; sec=None
    for line in txt.split("\n"):
        if re.match(r"^[A-Z][A-Za-z ]*:\s*$", line): sec=line.strip()[:-1]; continue
        if sec=="Commands":
            m=re.match(r"^  ([a-z][a-z0-9-]*)\s", line)
            if m and m.group(1)!="help": cmds.append(m.group(1))
            m2=re.search(r"\[aliases?: ([^\]]+)\]", line)
            if m2 and cmds: cmds += [a.strip() for a in m2.group(1).split(",")]
        if sec=="Options" or sec=="Arguments" or (sec and "Options" in sec):
            m=re.match(r"^\s{2,6}(-[A-Za-z0-9],\s+)?(--[A-Za-z0-9-]+)?(?:[ =](\[?<[^>]+>\]?(?:\.\.\.)?))?", line)
            if m and (m.group(1) or m.group(2)):
                val=m.group(3)
                kind="flag" if not val else ("optional" if val.startswith("[") else ("variadic" if val.endswith("...") else "value"))
                for n in [m.group(1) and m.group(1).strip(" ,"), m.group(2)]:
                    if n: opts[n]=kind
    return cmds, opts
HOME=tempfile.mkdtemp(prefix="cxhelp-"); os.makedirs(os.path.join(HOME,".codex"),exist_ok=True)
out={}
def walk(path, depth):
    cmds,opts=parse(help_of(path))
    out[" ".join(path) or "<root>"]={"opts":opts,"cmds":sorted(set(cmds))}
    if depth<2:
        for c in sorted(set(cmds)):
            if c in ("a","e"): continue
            walk(path+[c], depth+1)
walk([],0)
version=subprocess.run([B,"--version"],capture_output=True,text=True,env={"PATH":"/usr/bin:/bin","HOME":HOME}).stdout.strip().split()[-1]
lines=["// GENERATED by scripts/gen-codex-cli-table.py from `codex <path> --help` of codex "+version+" (ACCOUNTS-2 round 8) — do not edit by","// hand; regenerate for a new Codex version. Per command path: every option with how it takes values, and the","// subcommands. The routing-pin placement (codex-routing.ts) refuses credentials for a flag this table does not know.","","export type OptKind = \"flag\" | \"value\" | \"optional\" | \"variadic\";","export interface CodexCommand { opts: Readonly<Record<string, OptKind>>; cmds: readonly string[] }","","export const CODEX_VERSION_TABLE = \""+version+"\";","export const CODEX_CLI: Readonly<Record<string, CodexCommand>> = {"]
for k in sorted(out):
    v=out[k]; key="" if k=="<root>" else k
    opts=", ".join(f'{json.dumps(n)}: {json.dumps(t)}' for n,t in sorted(v["opts"].items()))
    cmds=", ".join(json.dumps(c) for c in v["cmds"])
    lines.append(f"  {json.dumps(key)}: {{ opts: {{ {opts} }}, cmds: [{cmds}] }},")
lines.append("};")
dest=os.path.join(os.path.dirname(os.path.abspath(__file__)),"..","src","switch","codex-cli-table.ts")
open(dest,"w").write("\n".join(lines)+"\n")
for k,v in out.items():
    vals={n:t for n,t in v["opts"].items() if t!="flag"}
    print(k, "| cmds:", ",".join(v["cmds"]) or "-", "| value opts:", json.dumps(vals))
